version: "2"
services:
  pkg_sender:
    build: .
    container_name: ps4_pkg_sender
    volumes:
      - ./files:/opt/apps/pkg_sender/files
      - /srv/dev-disk-by-uuid-820dec2c-37a0-45b3-af55-34fb34afe767/:/HDD1
      - /srv/dev-disk-by-uuid-1913d119-ecc4-41e4-b936-348064e82870/:/HDD3
    ports:
      - 3333:8033
    environment:
      - PORT=8033
      - STATIC_FILES=/opt/apps/pkg_sender/files
      - LOCALIP=192.168.0.108
      - PS4IP=192.168.0.109
    restart: unless-stopped
