version: "2"
services:
  pkg_sender:
    build: .
    container_name: pkg_sender
    volumes:
      - ./files:/opt/apps/pkg_sender/files
    ports:
      - 3333:8033
    environment:
      - PORT=8033
      - STATIC_FILES=/opt/apps/pkg_sender/files
      - LOCALIP=192.168.0.108
      - PS4IP=192.168.0.109
    restart: unless-stopped
