version: "2"
services:
  pkg_sender:
    build: .
    container_name: pkg_sender
    network_mode: host
    volumes:
      - /files:/srv/dev-disk-by-uuid-820dec2c-37a0-45b3-af55-34fb34afe767/PS4Roms
    ports:
      - 3333:8033
    environment:
      - PORT=8033
      - STATIC_FILES=/srv/dev-disk-by-uuid-820dec2c-37a0-45b3-af55-34fb34afe767/PS4Roms
      - LOCALIP=192.168.0.108
      - PS4IP=192.168.0.109
    restart: unless-stopped
